Adding SupplierPartAuxilaryId and option to change operationAllowed
hscheffknecht/cxml pull request #2
Opened 2022-03-16 08:52 UTC by MarioShatterhand

2022-03-16 08:54 UTC, MarioShatterhand commented
Second commit is also mine, I was just log in on wrong account

2022-03-16 12:44 UTC, hscheffknecht requested changes

2022-03-16 12:44 UTC, hscheffknecht commented on src/CXml/Models/Messages/PunchOutOrderMessageHeader.php
> +    /**
Please add here an empty line

2022-03-16 12:44 UTC, hscheffknecht commented on src/CXml/Models/Messages/PunchOutOrderMessageHeader.php
> +    private $operationAllowed;
Could you please add `'create'` as default value for backward compatibility (for the case `operationAllowed` is not set)?

2022-03-16 19:21 UTC, MarioShatterhand commented on src/CXml/Models/Messages/PunchOutOrderMessageHeader.php
> +    private $operationAllowed;
I've added a default value

2022-03-16 19:21 UTC, MarioShatterhand commented on src/CXml/Models/Messages/PunchOutOrderMessageHeader.php
> +    /**
Done

2022-03-17 20:26 UTC, hscheffknecht commented
Thanks!

2022-03-17 20:27 UTC, merged